# Generated by Django 5.1.7 on 2025-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredhost',
            name='last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
