# Generated by Django 5.1.7 on 2025-04-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_plugin', '0002_discoveredhost_last_fetched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoveredhost',
            name='last_fetched',
        ),
    ]
