# Generated by Django 5.1.7 on 2025-04-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_plugin', '0003_remove_discoveredhost_last_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredhost',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
