# Generated by Django 5.1.7 on 2025-04-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_zabbix_plugin', '0004_discoveredhost_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discoveredhost',
            old_name='type',
            new_name='os',
        ),
    ]
